### ISSUE TITLE
Relationship to ocaml-uring

### ISSUE THREAD

**Issue by talex5** [mt-caret/io_uring#8]
Hi,

We recently added our own uring bindings to opam-repository, and I just wanted to check that you're aware of that, to avoid duplicating effort:

- https://github.com/ocaml-multicore/ocaml-uring/
- http://opam.ocaml.org/packages/uring/

I'm not sure what license this project is, but ours is ISC, so we could combine bits if yours is the same.

**Comment by mt-caret** [comment]
Hi! Thanks for the heads-up! I think I became aware of ocaml-multicore/ocaml-uring sometime after starting work on this.

This library was written as to be easier to integrate into Async, which is why the completion API is different, and depend somewhat heavily on Base/Core conventions (i.e. making use of ppx_optional to avoid allocations). Given the somewhat different design choices, I was a bit hesitant to introduce these changes to ocaml-uring. That being said, I've just licensed the project under the same ISC license, and if you're OK/interested in integrating some things here into ocaml-uring, I'm happy to help.

**Comment by talex5** [comment]
OK, I'll close this then!
